#  taken from https://pythonhosted.org/pynput/_modules/pynput/keyboard/_base.html
#
#  edited with sed to match python-switch statement
# By: Ken Nguyen
from pynput.keyboard import Key

keys_map={
    Key.alt: 'down-alt',
    Key.alt_l: 'down-alt',
    Key.alt_r: 'down-alt',
    Key.alt_gr: 'down-alt',
    Key.backspace: 'press-backspace',
    Key.caps_lock: 'down-caps',
    Key.cmd: 'down-cmd',
    Key.cmd_l: 'down-cmd',
    Key.cmd_r: 'down-cmd',
    Key.ctrl: 'down-ctrl',
    Key.ctrl_l: 'down-ctrl',
    Key.ctrl_r: 'down-ctrl',
    Key.delete: 'press-delete',
    Key.down: 'press-down',
    Key.end: 'press-end',
    Key.enter: 'press-enter',
    Key.esc: 'press-esc',
    Key.f1: 'press-f1',
    Key.f2: 'press-f2',
    Key.f3: 'press-f3',
    Key.f4: 'press-f4',
    Key.f5: 'press-f5',
    Key.f6: 'press-f6',
    Key.f7: 'press-f7',
    Key.f8: 'press-f8',
    Key.f9: 'press-f9',
    Key.f10: 'press-f10',
    Key.f11: 'press-f11',
    Key.f12: 'press-f12',
    Key.f13: 'press-f13',
    Key.f14: 'press-f14',
    Key.f15: 'press-f15',
    Key.f16: 'press-f16',
    Key.f17: 'press-f17',
    Key.f18: 'press-f18',
    Key.f19: 'press-f19',
    Key.f20: 'press-f20',
    Key.home: 'press-home',
    Key.left: 'press-left',
    Key.page_down: 'press-page',
    Key.page_up: 'press-page',
    Key.right: 'press-right',
    Key.shift: 'down-shift',
    Key.shift_l: 'down-shift',
    Key.shift_r: 'down-shift',
    Key.space: 'press-space',
    Key.tab: 'press-tab',
    Key.up: 'press-up',
    Key.insert: 'press-insert',
    Key.menu: 'press-menu',
    Key.num_lock: 'press-num',
    Key.pause: 'press-pause',
    Key.print_screen: 'press-print',
    Key.scroll_lock: 'press-scroll'
}

keys_command=(
    'down-alt',
    'down-caps',
    'down-cmd',
    'down-ctrl',
    'down-shift',
    'press-backspace',
    'press-delete',
    'press-down',
    'press-end',
    'press-enter',
    'press-esc',
    'press-f1',
    'press-f10',
    'press-f11',
    'press-f12',
    'press-f13',
    'press-f14',
    'press-f15',
    'press-f16',
    'press-f17',
    'press-f18',
    'press-f19',
    'press-f2',
    'press-f20',
    'press-f3',
    'press-f4',
    'press-f5',
    'press-f6',
    'press-f7',
    'press-f8',
    'press-f9',
    'press-home',
    'press-insert',
    'press-left',
    'press-menu',
    'press-num',
    'press-page',
    'press-pause',
    'press-print',
    'press-right',
    'press-scroll'
    'press-space',
    'press-tab',
    'press-up',
)
