# pynput of the host does not auto accept special keys as string 
# this module convert the Object into the right String to send to server
# Author: Ken Nguyen
from pynput.keyboard import Key

def switch_key(keyCode):
    return {
        Key.alt: 'alt',
        Key.alt_l: 'alt',
        Key.alt_r: 'alt',
        Key.alt_gr: 'alt',
        Key.backspace: 'backspace',
        Key.caps_lock: 'caps',
        Key.cmd: 'cmd',
        Key.cmd_l: 'cmd',
        Key.cmd_r: 'cmd',
        Key.ctrl: 'ctrl',
        Key.ctrl_l: 'ctrl',
        Key.ctrl_r: 'ctrl',
        Key.delete: 'delete',
        Key.down: 'down',
        Key.end: 'end',
        Key.enter: 'enter',
        Key.esc: 'esc',
        Key.f1: 'f1',
        Key.f2: 'f2',
        Key.f3: 'f3',
        Key.f4: 'f4',
        Key.f5: 'f5',
        Key.f6: 'f6',
        Key.f7: 'f7',
        Key.f8: 'f8',
        Key.f9: 'f9',
        Key.f10: 'f10',
        Key.f11: 'f11',
        Key.f12: 'f12',
        Key.f13: 'f13',
        Key.f14: 'f14',
        Key.f15: 'f15',
        Key.f16: 'f16',
        Key.f17: 'f17',
        Key.f18: 'f18',
        Key.f19: 'f19',
        Key.f20: 'f20',
        Key.home: 'home',
        Key.left: 'left',
        Key.page_down: 'page',
        Key.page_up: 'page',
        Key.right: 'right',
        Key.shift: 'shift',
        Key.shift_l: 'shift',
        Key.shift_r: 'shift',
        Key.space: 'space',
        Key.tab: 'tab',
        Key.up: 'up',
        Key.insert: 'insert',
        Key.menu: 'menu',
        Key.num_lock: 'num',
        Key.pause: 'pause',
        Key.print_screen: 'print',
        Key.scroll_lock: 'scroll',
    }.get(keyCode, None)


